server:
  port: 8081
spring:
  docker:
    compose:
      file: ./backend/compose.yaml

  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:9090/realms/talibhub-realm/protocol/openid-connect/certs
          issuer-uri: http://localhost:9090/realms/talibhub-realm
  jpa:
    show-sql: true
