jwt:
  key: "YourSecretKeyHereYourSecretKeyHereYourSecretKeyHereYourSecretKeyHere"
  access-token-expiration-in-minutes: 10
  refresh-token-expiration-in-days: 30
spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true