server:
  port: 8081
spring:
  jpa:
    hibernate:
      ddl-auto: update
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration
  docker:
    compose:
      file: ./backend/compose.yaml